"""baseline schema

Revision ID: 09d0a37b13a1
Revises:
Create Date: 2026-07-02 12:04:42.883669
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09d0a37b13a1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("active_provider", sa.String(), nullable=False),
        sa.Column("provider_mode", sa.String(), nullable=False),
        sa.Column("ollama_base_url", sa.String(), nullable=False),
        sa.Column("ollama_model", sa.String(), nullable=False),
        sa.Column("cloud_model", sa.String(), nullable=True),
        sa.Column("cloud_key_ref", sa.String(), nullable=True),
        sa.Column("cloud_key_enc", sa.LargeBinary(), nullable=True),
        sa.Column("request_timeout_s", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("id = 1", name="ck_settings_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "learning_paths",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        sa.Column("estimated_hours", sa.Float(), nullable=True),
        sa.Column("generated_by", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("syllabus_json", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "path_steps",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("path_id", sa.String(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("resources_json", sa.String(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("done_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["path_id"], ["learning_paths.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path_id", "order_index", name="uq_step_order"),
    )
    with op.batch_alter_table("path_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_path_steps_path_id"), ["path_id"], unique=False
        )

    op.create_table(
        "calendar_entries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("step_id", sa.String(), nullable=False),
        sa.Column("path_id", sa.String(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("is_milestone", sa.Boolean(), nullable=False),
        sa.Column("sync_state", sa.String(), nullable=False),
        sa.Column("external_ref", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["path_id"], ["learning_paths.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["step_id"], ["path_steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("step_id", name="uq_calendar_step"),
    )
    with op.batch_alter_table("calendar_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calendar_entries_path_id"), ["path_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_calendar_entries_scheduled_date"),
            ["scheduled_date"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calendar_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calendar_entries_scheduled_date"))
        batch_op.drop_index(batch_op.f("ix_calendar_entries_path_id"))

    op.drop_table("calendar_entries")
    with op.batch_alter_table("path_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_path_steps_path_id"))

    op.drop_table("path_steps")
    op.drop_table("learning_paths")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
